trigger:
  branches:
    include:
    - main  # Adjust branch name as necessary
  paths:
    include:
    - ./charts/bestrong-api  # Adjust path as necessary
pool:
  vmImage: 'ubuntu-latest'


variables:
  acrName: 'helmcontainer'  # Add your Azure Container Registry name
  serviceConnection: 'Azure for Students(12c692a0-00e1-447a-8d87-2712018a0472)'  # Name of the Azure service connection


steps:
- task: HelmInstaller@1
  inputs:
    helmVersionToInstall: '3.x'

- task: AzureCLI@2
  inputs:
    azureSubscription: $(serviceConnection)
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo 'Logging into Azure Container Registry'
      az acr login --name helmcontainer.azurecr.io
  displayName: 'Login to ACR'
- task: HelmDeploy@0
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'aks'
    namespace: 'default'
    command: 'install'
    chartType: 'FilePath'
    chartPath: 'oci://helmcontainer.azurecr.io/helm/bestrong-api'
    releaseName: 'myhelmtest'
    version: '184'
  displayName: 'Deploy Helm chart'

