trigger:
  branches:
    include:
    - main  # Adjust branch name as necessary
  paths:
    include:
    - ./charts/bestrong-api  # Adjust path as necessary
pool:
  vmImage: 'ubuntu-latest'


variables:
  registryName: 'HelmContainer.azurecr.io'
  repository: 'helmcontainer'
  chartName: 'bestrong-api'
  clusterServiceConnection: 'aks'
  namespace: 'default'  
steps:
- task: HelmDeploy@0
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'aks'
    namespace: 'default'
    command: 'upgrade'
    chartName: 'HelmContainer.azurecr.io/bestrong-api'
    releaseName: 'bestrong-api'
    arguments: '--version 174'


