trigger:
  branches:
    include:
    - main  # Adjust branch name as necessary
  paths:
    include:
    - ./charts/bestrong-api  # Adjust path as necessary

pool:
  vmImage: 'ubuntu-latest'

variables:
  acrName: 'helmcontainer'  # Add your Azure Container Registry name
  serviceConnection: 'azsc'  # Name of the Azure service connection

steps:
- task: HelmInstaller@0
  inputs:
    helmVersion: '3.14.4'
    installKubectl: true

- script: |
    echo "Packaging Helm charts..."
    cd ./charts/bestrong-api # Navigate to the Helm chart directory
    pwd
    helm package . --version $(Build.BuildId) --destination .  # Package the chart, no need to specify version here
    ls
  displayName: 'Package Helm Chart'

- task: AzureCLI@2
  inputs:
    azureSubscription: $(serviceConnection)
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "Logging into Azure Container Registry..."
      az acr login --name $(acrName)
      cd ./charts/bestrong-api # Navigate to the Helm chart directory
      pwd
      ls
      echo "Pushing Helm chart to Azure Container Registry as OCI artifact..."
      helm push bestrong-api-$(Build.BuildId).tgz oci://$(acrName).azurecr.io/mychart
  displayName: 'Push Helm Chart as OCI Artifact'
