trigger:
  branches:
    include:
    - main  # Adjust branch name as necessary
  paths:
    include:
    - ./charts/bestrong-api  # Adjust path as necessary

pool:
  vmImage: 'ubuntu-latest'

variables:
  acrName: 'HelmContainer'  # Add your Azure Container Registry name

steps:
- task: HelmInstaller@0
  inputs:
    helmVersion: '2.14.1'
    installKubectl: true

- script: |
    echo "Packaging Helm charts..."
    cd ./charts/bestrong-api # Navigate to the Helm chart directory
    helm package . --version $(Build.BuildId)
  displayName: 'Package Helm Chart'

- script: |
    echo "Packaging Helm charts..."
    cd ./helm-charts/bestrong-api  
    helm package . --version $(Build.BuildId)
    echo "Converting Helm chart to OCI format..."
    helm chart save . $(acrName).azurecr.io/mychart:$(Build.BuildId)
    echo "Pushing Helm chart to Azure Container Registry as OCI artifact..."
    helm chart push $(acrName).azurecr.io/mychart:$(Build.BuildId)
  displayName: 'Package and Push Helm Chart as OCI Artifact'


