trigger:
  branches:
    include:
    - main  # Adjust branch name as necessary
  paths:
    include:
    - ./charts/bestrong-api  # Adjust path as necessary

pool:
  vmImage: 'ubuntu-latest'

variables:
  acrName: 'HelmContainer'  # Add your Azure Container Registry name

steps:
- task: HelmInstaller@0
  inputs:
    helmVersion: '2.14.1'
    installKubectl: true

- script: |
    echo "Packaging Helm charts..."
    cd ./charts\bestrong-api # Navigate to the Helm chart directory
    helm package . --version $(Build.BuildId)
  displayName: 'Package Helm Chart'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure for Students(12c692a0-00e1-447a-8d87-2712018a0472)'  # Name of the Azure service connection
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "Pushing Helm chart to Azure Container Registry..."
      az acr helm push $(Build.BuildId)-mychart.tgz --name $(acrName)
  displayName: 'Push Helm Chart to ACR'

