trigger:
  branches:
    include:
    - main  # Adjust branch name as necessary
  paths:
    include:
    - ./charts/bestrong-api  # Adjust path as necessary
pool:
  vmImage: 'ubuntu-latest'


variables:
  registryName: 'HelmContainer.azurecr.io'
  repository: 'helmcontainer'
  chartName: 'bestrong-api'
  clusterServiceConnection: 'aks'
  namespace: 'default'

steps:

- task: HelmDeploy@0
  displayName: 'Helm upgrade'
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceConnection: '$(clusterServiceConnection)'
    namespace: '$(namespace)'
    command: 'upgrade'
    chartType: 'Name'
    chartName: '$(registryName)/$(repository)/$(chartName)'
    releaseName: 'bestrong-api-release'
    waitForExecution: true
    arguments: '--install'


- task: HelmDeploy@0
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscription: 'Azure for Students(12c692a0-00e1-447a-8d87-2712018a0472)'
    azureResourceGroup: 'aks'
    kubernetesCluster: 'vit'
    command: 'ls'