trigger:
  branches:
    include:
    - main  # Adjust branch name as necessary
  paths:
    include:
    - ./charts/bestrong-api  # Adjust path as necessary

pool:
  vmImage: 'ubuntu-latest'

variables:
  acrName: 'HelmContainer'  # Add your Azure Container Registry name

steps:
- task: HelmInstaller@0
  inputs:
    helmVersion: '3.14.4'
    installKubectl: true

- script: |
    echo "Packaging Helm charts..."
    cd ./charts/bestrong-api # Navigate to the Helm chart directory
    helm package . --version $(Build.BuildId) --destination .  # Package the chart, no need to specify version here
  displayName: 'Package Helm Chart'

- script: |
    echo "Pushing Helm chart to Azure Container Registry as OCI artifact..."
    helm push bestrong-api-$(Build.BuildId).tgz oci://$(acrName).azurecr.io/mychart
  displayName: 'Push Helm Chart as OCI Artifact'
