trigger:
  branches:
    include:
    - main  # Adjust branch name as necessary
  paths:
    include:
    - ./charts/bestrong-api  # Adjust path as necessary
pool:
  vmImage: 'ubuntu-latest'


variables:
  containerRegistry: 'helmcontainer'  # Add your Azure Container Registry name
  serviceConnection: 'Azure for Students(12c692a0-00e1-447a-8d87-2712018a0472)'  # Name of the Azure service connection


steps:
- task: HelmInstaller@0
  inputs:
    helmVersion: '3.14.4'
    installKubectl: true

- task: AzureCLI@2
  inputs:
    azureSubscription: $(serviceConnection)
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo 'Logging into Azure Container Registry'
      az acr login --name helmcontainer.azurecr.io
  displayName: 'Login to ACR'
- task: HelmDeploy@0
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceConnection: 'aks'
    namespace: 'default'
    command: 'upgrade'
    chartType: 'Name'
    chartName: 'myhelmtest'
    releaseName: 'myhelmtest'
    valueFile: 'values.yaml'
    arguments: '--install --version 184 --repo oci://$(containerRegistry)/helm'
  displayName: 'Install/Upgrade Helm Chart'

- script: |
    kubectl get services
  displayName: 'List Kubernetes Services'


