trigger:
  branches:
    include:
    - main  # Adjust branch name as necessary
  paths:
    include:
    - ./charts/bestrong-api  # Adjust path as necessary
pool:
  vmImage: 'ubuntu-latest'

 
variables:
  aksClusterName: 'AKSCluster'
  aksResourceGroup: 'AKSUitware'
  acrName: 'helmcontainer'
  chartName: 'bestrong-api'
  chartVersion: '174'
  helmReleaseName: 'bestrong-api-release'
  serviceConnection: 'Azure for Students(12c692a0-00e1-447a-8d87-2712018a0472)'

stages:
- stage: Deploy
  jobs:
  - job: DeployToAKS
    pool:
      vmImage: 'ubuntu-latest'
    steps:

    # Authenticate to Azure CLI
    - task: AzureCLI@2
      inputs:
        azureSubscription: $(serviceConnection)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az acr login --name $(acrName)
          helm repo add $(acrName) https://$(acrName).azurecr.io/$(chartName)
          helm repo update
      displayName: 'Add ACR Helm repository'

    # Install or upgrade Helm release
    - task: HelmDeploy@0
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: 'aks'
        namespace: '<Your-Kubernetes-Namespace>'
        command: 'upgrade'
        chartName: '$(acrName).azurecr.io/$(chartName)'
        releaseName: '$(helmReleaseName)'
        arguments: '--install --version $(chartVersion)'
        valueFile: 'values-prod.yaml'

