# Deployment configurations  
stable:
  replicas: 2
  version: v1
  containerSpecImagePullPolicy: Always
  containerName: bestrong
  image: nginx #nginx #maksymperehinets/bestrong-api
  imageTag: latest
  resources:
    requestsMemory: 50Mi
    requestsCpu: 50m
    limitsMemory: 90Mi
    limitsCpu: 100m
  port: 80

# Canary roll out policy
canary:
  timeBeforeRollBack: 60
  servicePort: 80
  interval: 15s
  maxFailed: 5
  maxTraficRouted: 50
  stepWeight: 15
  minRequestsSuccessRate: 90
  cheakIntervall: 2m

# Specify ingress configuration for targets and path
ingress:
  target: /
  ingressPath: /
  pathType: ImplementationSpecific
  clasteIssuareName: "letsencrypt-prod"
  hostname: test-molip.duckdns.org
clusterIssuer:
  email: vitalikstelmah60@gmail.com
  server: "https://acme-v02.api.letsencrypt.org/directory"
  privateKeySecretName: "letsencrypt-prod-key"
