# Deployment configurations
stable:
  replicas: 2
  version: v1
  containerSpecImagePullPolicy: Always s
  containerName: bestrong 
  image: maksymperehinets/bestrong-api
  imageTag: latest 
  resources:
    requestsMemory: 250Mi 
    requestsCpu: 250m 
    limitsMemory: 500Mi 
    limitsCpu: 500m 
  port: 80

# Deployment configurations
canary:
  replicas: 0
  version: v2
  containerSpecImagePullPolicy: Always 
  containerName: bestrong 
  image: nginx 
  imageTag: latest 
  resources:
    requestsMemory: 250Mi 
    requestsCpu: 250m 
    limitsMemory: 500Mi 
    limitsCpu: 500m 
  port: 80 

# Service configuration
service: 
  port: 80 

# Specify ingress configuration for targets and path
ingress:
  target: /
  ingressPath: /
  pathType: ImplementationSpecific
  clasteIssuareName: "letsencrypt-prod"
  hostname: bestrong.eastus.cloudapp.azure.com
  tlsSercret: jlkjsdfjirj


clusterIssuer:
  email: vitalikstelmah60@gmail.com
  server: "https://acme-v02.api.letsencrypt.org/directory"
  privateKeySecretName: "letsencrypt-prod-key"
