apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: kube-system
data:
  fluent.conf: |
    # <source>
    #   @type tail
    #   path /var/log/containers/*bestrong*.log
    #   pos_file /var/log/es-containers.log.pos
    #   path_key log
    #   tag kubernetes.*
    #   format json
    #   follow_inodes true
    #   read_from_head true
    #   time_format %Y-%m-%dT%H:%M:%S.%NZ
    # </source>

    # <match **>
    #   @type elasticsearch
    #   host elasticsearch-master.monitoring.svc.cluster.local
    #   port 9200
    #   logstash_format true
    #   flush_interval 10s
    # </match>

    # <match **>
    #   @type stdout
    # </match>

    <match fluent.>
      @type null
    </match>

    <source>
      @type tail
      path /var/log/containers/*bestrong*.log
      pos_file /var/log/fluentd-containers.log.pos
      time_format %Y-%m-%dT%H:%M:%S.%NZ
      tag kubernetes.*
      format json
      read_from_head true
    </source>

    <filter kubernetes.>
      @type kubernetes_metadata
    </filter>

    <match **>
      @type elasticsearch
      host elasticsearch-master.logging.svc.cluster.local
      port 9200
      logstash_format true
      flush_interval 10s
    </match>

    <match **>
      @type stdout
    </match>
    