defaultRules:
  create: true
  rules:
    windows: false

prometheus:
  prometheusSpec:
    ruleSelector:
       matchExpressions:
        - key: prometheus
          operator: In
          values:
          - alert-rule


alertmanagerSpec:
  alertmanagerConfigSelector:
    matchExpressions:
      - key: alertconfig
        operator: In
        values:
          - "true"

grafana:
  enabled: true
  namespaceOverride: ""
  defaultDashboardsTimezone: utc
  adminPassword: test123

  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      kubernetes.io/ingress.class: traefik
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - grafanabestrong.duckdns.org
    tls:
      - hosts:
          - grafanabestrong.duckdns.org
        secretName: grafana-tls
    


