trigger:
  branches:
    include:
    - main  
  paths:
    include:
    - charts/bestrong-api/*
    exclude:
      - "*"



variables:
  acrName: 'helmcontainer'  # Add your Azure Container Registry name
  serviceConnection: 'Azure for Students(12c692a0-00e1-447a-8d87-2712018a0472)'  # Name of the Azure service connection


stages:
- stage: PackHelmChart
  displayName: Helm chart packing and push to ACR 
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
  - job: Helm_install_pack_and_push
    displayName: Helm install pack and push to ACR
    steps:
      - template: templates/build.yaml
        parameters:
          acrName: $(acrName)
          serviceConnection: $(serviceConnection)

- stage: PushAKS
  displayName: Upgrade AKS deployment to new chart version
  condition: succeeded('PackHelmChart')
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
  - job: UpdateChartOnAKS
    displayName: Update or install helm chart to new version(one that was built previously) in AKS 
    steps:
      - template: templates/push_to_aks.yaml
        parameters:
          acrName: $(acrName)
          serviceConnection: $(serviceConnection)