trigger:
  branches:
    include:
    - main  
  paths:
    include:
    - charts/bestrong-api/*
    - monitoring/*
    - logging/*
    exclude:
      - "*"

variables:
  acrName: 'helmcontainer'  # Add your Azure Container Registry name
  serviceConnection: 'Azure for Students(12c692a0-00e1-447a-8d87-2712018a0472)'  # Name of the Azure service connection


stages:
- stage: BootstrapDepend
  displayName: Bootstrap dependencies 
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
  - job: Create namaspace install fluentd and configure it
    displayName: Helm install pack and push to ACR
    steps:
      - template: templates/dependecies.yaml
        parameters:
          acrName: $(acrName)
          serviceConnection: $(serviceConnection)

- stage: PackHelmChart
  displayName: Helm chart packing and push to ACR 
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
  - job: Helm_install_pack_and_push
    displayName: Helm install pack and push to ACR
    steps:
      - template: templates/build.yaml
        parameters:
          acrName: $(acrName)
          serviceConnection: $(serviceConnection)
  - job: Update_prometheus_alert_rules
    displayName: Update or create config for prometheus alerts
    steps:
      - task: KubernetesManifest@0
        displayName: Deploy K8s manifests
        inputs:
          namespace: monitoring
          manifests: ./monitoring/alert-config.yaml
          kubernetesServiceConnection: aks


- stage: PushAKS
  displayName: Upgrade AKS deployment to new chart version
  condition: succeeded('PackHelmChart')
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
  - job: UpdateChartOnAKS
    displayName: Update or install helm chart to new version(one that was built previously) in AKS 
    steps:
      - template: templates/push_to_aks.yaml
        parameters:
          acrName: $(acrName)
          serviceConnection: $(serviceConnection)