replicaCount: 2

image:
  repository: bestrongdockeracr6ep0b2yp.azurecr.io/vitaliistelmakhaspnetcorewebapisample
  tag: 145
  pullSecret: acr-auth

service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/rewrite-target: "/"
  hosts:
    - host: "peetro.eastus.cloudapp.azure.com"
      paths:
        - path: "/"
          pathType: Prefix

clusterIssuer:
  email: vitalikstelmah60@gmail.com
  server: "https://acme-v02.api.letsencrypt.org/directory"
  privateKeySecretName: "letsencrypt-prod-key"
